name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
   runs-on: windows-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Build with Gradle
        run : ./gradlew build
        
      - name: Upload APK File  
        uses: actions/upload-artifact@v4.3.1
        with:
            name: dsTemplate.apk 
            path: app/build/outputs/apk/debug/app-debug.apk
                  
      
     
