name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
   runs-on: window-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Setup JDK  
        uses: actions/setup-java@1.0.0
        with:
            java-version: 1.8
      - name : Build with Gradle   
        run: ./gradlew build
      - name: Upload APK  
        uses: actions/upload-artifact@v4.3.1
        with:
            name: app
            path: app/buil/outputs/apk/debug/app-debug.apk
      
     
